### ISSUE TITLE
Python 3.8 support

### ISSUE THREAD

**Issue by dmvieira** [olxbr/BarterDude#29]
Nowadays python 3.8 tests are broken because of json logger: https://travis-ci.com/github/olxbr/BarterDude/jobs/346357213

**Comment by tirkarthi** [comment]
Seems to be fixed with https://github.com/madzak/python-json-logger/commit/35a8ca2c9ae4935255442dbbc6d90a15c5ce08c9

**Comment by dmvieira** [comment]
I'll try an PR here with it. Thank you @tirkarthi !
